export const MESSAGE = "MESSAGE";
export const GET_ALL_CUSTOMER = "GET_ALL_CUSTOMER";
export const GET_ALL_ITEM = "GET_ALL_ITEM";
export const GET_ALL_REPLACEMENT_PARTNER = "GET_ALL_REPLACEMENT_PARTNER";
